const ACTION = {
    ADD_ITEM: "ADD_ITEM",
    UPDATE_ITEM_QAUNTITY: "UPDATE_ITEM_QAUNTITY",
    INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
    DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
    REMOVE_ITEM: "REMOVE_ITEM",
    GET_TOTAL: "GET_TOTAL",
    CLEAR_CART: "CLEAR_CART",
}

export default ACTION