const ACTION = {
   GET_ALL_PRODUCTS_LOADING : "GET_ALL_PRODUCTS_LOADING",
   GET_ALL_PRODUCTS_SUCCESS : "GET_ALL_PRODUCTS_SUCCESS",
   GET_ALL_PRODUCTS_FAILED : "GET_ALL_PRODUCTS_FAILED",

   GET_SINGLE_PRODUCT_LOADING : "GET_SINGLE_PRODUCT_LOADING",
   GET_SINGLE_PRODUCT_SUCCESS : "GET_SINGLE_PRODUCT_SUCCESS",
   GET_SINGLE_PRODUCT_FAILED : "GET_SINGLE_PRODUCT_FAILED",
   GET_SINGLE_PRODUCT_RESET : "GET_SINGLE_PRODUCT_RESET",
}

export default ACTION