const ACTION = {
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    UPDATE_ITEM_QAUNTITY: "UPDATE_ITEM_QAUNTITY",
    GET_TOTAL: "GET_TOTAL",
    CLEAR_CART: "CLEAR_CART",
}

export default ACTION